### ISSUE TITLE
Featured image not appearing

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/hbsc#38]
The featured image added to this page is not showing up on the site: http://hbstowecenter.wpengine.com/why-visit-the-stowe-center/

**Comment by Jessdwilson** [comment]
I've noticed this on a few other pages as well, can all default template pages have this option?

**Comment by joauv** [comment]
Because of design demands, most pages currently do not use a 'default' template (they have their own unique file relative to their URL). The actual default template (Pages>Add New) has the possibility of adding a featured image right after the first section and before modules.

Can you confirm you want _all_ existing pages to have the possibility of displaying a featured image (right after the first section)?

**Comment by Jessdwilson** [comment]
Hi @joauv If it's possible, it would be great if Default template pages could have the option to display a featured image. I think it's confusing for the client to see Featured Image displayed as an option in Wordpress for all pages shown using Default template, if these pages cannot display a featured image can that section be removed so the client doesn't think it's broken? 

<img width="289" alt="screen shot 2017-08-09 at 3 20 05 pm" src="https://user-images.githubusercontent.com/1680051/29139957-c4aabe32-7d16-11e7-918f-eae5939c0c74.png">
